version: '3'
services:
  client:
    image: ultrayoshi/dogtector-client
    networks:
      - frontend
    labels:
      - "traefik.port=80"
  server:
    image: ultrayoshi/dogtector-server
    networks:
      - backend
    labels:
      - "traefik.port=3001"
  redis:
    image: redis
    networks:
      - backend
    labels:
      - "traefik.enable=false"
  reverse-proxy:
    image: traefik
    command: --api --docker
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - overlay
      - frontend
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=false"
networks:
  overlay:
  frontend:
  backend:
