version: '3'
services:
  client:
    build:
      context: client
      dockerfile: Dockerfile
      args:
        - node_env=development
    volumes:
      - ./client:/code
    labels:
      - "traefik.frontend.rule=Path:/dogtector"
      - "traefik.frontend.rule=ReplacePathRegex:^/dogtector/(.*) /$$1"
  server:
    build:
      context: server
      args:
        - node_env=development
    volumes:
      - ./server:/code
    labels:
      - "traefik.frontend.rule=Path:/dogtector-api"
      - "traefik.frontend.rule=ReplacePathRegex:^/dogtector-api/(.*) /$$1"
