version: '3'
services:
  client:
    build:
      context: client
      dockerfile: Dockerfile
      args:
        - node_env=development
    volumes:
      - ./client:/code
    labels:
      - "traefik.frontend.rule=PathPrefix:/dogtector"
  server:
    build:
      context: server
      args:
        - node_env=development
    volumes:
      - ./server:/code
    labels:
      - "traefik.frontend.rule=PathPrefix:/dogtector-api;PathPrefixStrip:/dogtector-api"
